### ISSUE TITLE
file not found ;)

### ISSUE THREAD

**Issue by ddaydd** [jesse-c/Arduino-DDP#2]
Hi,

`fatal error: /Users/jesse/Dropbox/university/engg4802/src/examples/pwm/hardware/pwm/libs/Arduino-Websocket/WebSocketClient.h: No such file or directory`

and

```
DDP.h:82:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
     StaticJsonBuffer<200> _jsonBuffer;
```

**Comment by jesse-c** [comment]
You'll need to see the https://github.com/jesse-c/Arduino-DDP#dependencies section and download them and then update the paths. You can try using them included as git submodules by I have not tested this.

**Comment by ddaydd** [comment]
wow, thanks for your reply, i didn't think you would reply so quickly :)

I'm on other mistakes ... arduinoJson is no longer compatible :)

**Comment by jesse-c** [comment]
No worries! Good luck. :)
